### ISSUE TITLE
duplicate dmarc for firezone.dev

### ISSUE THREAD

**Issue by gongjason** [firezone/firezone.dev#12]
@jamilbk do we need both of these?

https://github.com/firezone/firezone.dev/blob/242bce6567192ca1c3546c95199b07bb9947b88a/protonmail.tf#L53-L58

https://github.com/firezone/firezone.dev/blob/242bce6567192ca1c3546c95199b07bb9947b88a/google.tf#L1-L6

**Comment by jamilbk** [comment]
Nope, thanks for the catch. Updated and removed in #11
